export enum ActionTypes {
  ADD_NOTE = "ADD_NOTE",
  DELETE_NOTE = "DELETE_NOTE",
  UPDATE_NOTE = "UPDATE_NOTE",
  DELETE_ALL_NOTES = "DELETE_ALL_NODE",
  ARCHIVE_MODE = "ARCHIVE_MODE",
  SHOW_MODAL = "SHOW_MODAL",
  EDITING_NOTE = "EDITING_NOTE",
}
